"""Public host-adapter API for WireJac hardware orchestration."""

from .artifacts import ArtifactStore
from .commands import SubprocessRunner
from .discovery import DeviceDiscovery, discover_capabilities
from .esptool import EspToolAdapter, normalize_mac
from .host_runtime import (
    HostRuntime,
    artifact_path,
    backup_device,
    backup_and_provision_configured_device,
    build_simulation_image,
    capabilities_json,
    configure_runtime,
    deploy_bundle,
    deploy_and_verify_release,
    deploy_release,
    discover_devices_json,
    identify_device,
    persist_artifact,
    probe_micropython,
    provision_device,
    provision_configured_device,
    read_artifact,
    rollback_release,
    simulate_bundle,
    verify_device,
)
from .micropython_image import MicroPythonImageBuilder
from .models import (
    AdapterError,
    ArtifactConflictError,
    ArtifactRef,
    Capability,
    CapabilityReport,
    CapabilityUnavailableError,
    CommandExecutionError,
    CommandNotAllowedError,
    CommandResult,
    DeviceIdentity,
    DeviceLockError,
    DeviceSelectionError,
    FlashBackupResult,
    IdentityMismatchError,
    LittleFSProfile,
    MicroPythonImageResult,
    ProvisionResult,
    RestoreResult,
    RemoteHashResult,
    ResetResult,
    SafetyError,
    SerialCaptureResult,
    SerialDevice,
    SerialEvent,
    StageResult,
    StagedFile,
    VerificationError,
    WokwiControl,
    WokwiSimulationResult,
)
from .mpremote import DeviceFileLock, MpremoteAdapter
from .wokwi import WokwiAdapter

__all__ = [
    "AdapterError",
    "ArtifactConflictError",
    "ArtifactRef",
    "ArtifactStore",
    "artifact_path",
    "Capability",
    "CapabilityReport",
    "CapabilityUnavailableError",
    "CommandExecutionError",
    "CommandNotAllowedError",
    "CommandResult",
    "DeviceDiscovery",
    "DeviceFileLock",
    "DeviceIdentity",
    "DeviceLockError",
    "DeviceSelectionError",
    "EspToolAdapter",
    "FlashBackupResult",
    "HostRuntime",
    "IdentityMismatchError",
    "LittleFSProfile",
    "MicroPythonImageBuilder",
    "MicroPythonImageResult",
    "MpremoteAdapter",
    "ProvisionResult",
    "RestoreResult",
    "RemoteHashResult",
    "ResetResult",
    "SafetyError",
    "SerialCaptureResult",
    "SerialDevice",
    "SerialEvent",
    "StageResult",
    "StagedFile",
    "SubprocessRunner",
    "VerificationError",
    "WokwiAdapter",
    "WokwiControl",
    "WokwiSimulationResult",
    "backup_device",
    "backup_and_provision_configured_device",
    "build_simulation_image",
    "capabilities_json",
    "configure_runtime",
    "deploy_bundle",
    "deploy_and_verify_release",
    "deploy_release",
    "discover_capabilities",
    "discover_devices_json",
    "identify_device",
    "normalize_mac",
    "persist_artifact",
    "probe_micropython",
    "provision_device",
    "provision_configured_device",
    "read_artifact",
    "rollback_release",
    "simulate_bundle",
    "verify_device",
]
