def reviewed_phone_snatch_app() -> str: ...
def reviewed_motion_test_app() -> str: ...
def validate_application(source: str) -> list[str]: ...
def compile_bundle(
    app_source: str,
    build_id: str,
    ingest_url: str = ...,
    slot: str = ...,
    pin_sda: int = ...,
    pin_scl: int = ...,
    pin_led: int = ...,
    pin_button: int = ...,
) -> dict[str, str]: ...
def manifest_json(files: dict[str, str], build_id: str, slot: str) -> str: ...
def bundle_zip(files: dict[str, str], manifest: str) -> bytes: ...
def sha256_bytes(payload: bytes) -> str: ...
